name: first one

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install stable pip version
        run: python -m pip install pip==23.2.1

      - name: Install dependencies
        run: python -m pip install --disable-pip-version-check pytest

      - name: Run tests
        run: |
          cd src
          python -m pytest calc.py

